# Generated by Django 5.1.1 on 2024-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="learning_difficulty",
            field=models.CharField(max_length=255),
        ),
    ]
