# Generated by Django 5.1.1 on 2024-11-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activities",
            "0005_rename_correct_answers_childactivity_total_right_answers_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="findnumberstats",
            name="number",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                max_length=20,
            ),
        ),
    ]
