# Generated by Django 5.1.1 on 2024-11-23 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_alter_findnumberstats_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="findimagestats",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="findnumberstats",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="learnwithbuttonsstats",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="matchcolorstats",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="touchbodypartstats",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="findimagestats",
            name="attempt",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="findimagestats",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="findnumberstats",
            name="attempt",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="findnumberstats",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="learnwithbuttonsstats",
            name="attempt",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="learnwithbuttonsstats",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="matchcolorstats",
            name="attempt",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="matchcolorstats",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="touchbodypartstats",
            name="attempt",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="touchbodypartstats",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="findimagestats",
            name="child_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="find_image_stats",
                to="activities.childactivity",
            ),
        ),
        migrations.AlterField(
            model_name="findnumberstats",
            name="child_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="find_number_stats",
                to="activities.childactivity",
            ),
        ),
        migrations.AlterField(
            model_name="learnwithbuttonsstats",
            name="child_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="find_button_stats",
                to="activities.childactivity",
            ),
        ),
        migrations.AlterField(
            model_name="matchcolorstats",
            name="child_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_color_stats",
                to="activities.childactivity",
            ),
        ),
        migrations.AlterField(
            model_name="touchbodypartstats",
            name="child_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="touch_body_part_stats",
                to="activities.childactivity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="findimagestats",
            unique_together={("child_activity", "attempt", "image_type")},
        ),
        migrations.AlterUniqueTogether(
            name="findnumberstats",
            unique_together={("child_activity", "attempt", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="learnwithbuttonsstats",
            unique_together={("child_activity", "attempt", "button")},
        ),
        migrations.AlterUniqueTogether(
            name="matchcolorstats",
            unique_together={("child_activity", "attempt", "color")},
        ),
        migrations.AlterUniqueTogether(
            name="touchbodypartstats",
            unique_together={("child_activity", "attempt", "body_part")},
        ),
    ]
