# Generated by Django 5.1.1 on 2024-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_alter_findimagestats_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchcolorstats",
            name="color",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("black", "Black"),
                ],
                max_length=20,
            ),
        ),
    ]
