# Generated by Django 5.1.1 on 2024-12-23 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_matchcolorstats_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findimagestats',
            name='image_type',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('shapes', 'Shapes'), ('vehicles', 'Vehicles')], max_length=20),
        ),
        migrations.AlterField(
            model_name='findimagestats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 41, 25, 879298, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='findnumberstats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 41, 25, 879298, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='learnwithbuttonsstats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 41, 25, 879298, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='matchcolorstats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 41, 25, 879298, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='touchbodypartstats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 41, 25, 879298, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
