# Generated by Django 5.1.1 on 2024-12-23 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_alter_findimagestats_image_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findimagestats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 52, 55, 423415, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='findnumberstats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 52, 55, 423415, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='learnwithbuttonsstats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 52, 55, 423415, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='matchcolorstats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 52, 55, 423415, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='touchbodypartstats',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 52, 55, 423415, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
